package com.majchrosoft.homelibrary.domain.model

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A single library item — book, audiobook, board game, etc.
 *
 * Stored at `users/{ownerId}/items/{id}` in the Firebase Realtime Database. The
 * peculiar nested shape (`item`/`borrow` sub-objects) mirrors the legacy Angular
 * schema exactly so we can roll the KMP rewrite out without a data migration.
 *
 * Tree:
 * ```
 * users/
 *   {ownerId}/
 *     items/
 *       {id}/
 *         item/         ← descriptive fields (title, author, type, quality, ...)
 *         borrow/       ← embedded borrow state (isBorrowed, borrowedBy, ...)
 *         createdAt
 *         updatedAt
 * ```
 */
@Serializable
data class Item(
    /** Realtime DB push key — typically a `-N…` ID generated by Firebase. */
    val id: String = "",
    /** UID of the owning user. Mirrors the parent path under `users/{ownerId}`. */
    val ownerId: String = "",
    /** Descriptive fields about the item itself. */
    val item: ItemDetails = ItemDetails(),
    /** Borrow state — null/empty when the item is on the shelf. */
    val borrow: BorrowState = BorrowState(),
    @SerialName("createdAt") val createdAt: Instant? = null,
    @SerialName("updatedAt") val updatedAt: Instant? = null,
)

/** The descriptive payload stored under the nested `item` sub-object. */
@Serializable
data class ItemDetails(
    val title: String = "",
    val author: String = "",
    val type: ItemType = ItemType.BOOK,
    val quality: ItemQuality = ItemQuality.GOOD,
    /** ID reference to a [Bookcase] under `users/{ownerId}/bookcases/{bookcaseId}`. */
    val bookcase: String? = null,
    val isbn: String? = null,
    val publisher: String? = null,
    val publishedYear: Int? = null,
    val language: String? = null,
    val pages: Int? = null,
    val coverUrl: String? = null,
    val notes: String? = null,
    /** When true, this item is offered for borrowing by other users. */
    val shareable: Boolean = false,
)

/**
 * Embedded borrow state. The legacy Angular app keeps the borrow info on the item
 * itself rather than in a separate loan aggregate — we honor that here. A future
 * cross-user borrowing flow (other users on the platform requesting books) will add
 * a separate `loanRequests/` tree, but this struct stays the source of truth for
 * "is this item on my shelf right now".
 */
@Serializable
data class BorrowState(
    val isBorrowed: Boolean = false,
    /** Free-text or UID of the borrower — accepts both for legacy compatibility. */
    val borrowedBy: String? = null,
    val borrowedAt: Instant? = null,
    val dueAt: Instant? = null,
    val message: String? = null,
)
